version: '3.9'

services:
  frontend:
    image: knotnest_frontend:latest
    ports:
      - '3001:80'
    depends_on:
      - backend

  backend:
    image: knotnest_backend:latest
    ports:
      - '8001:8000'
