version: '3.9'

services:
  frontend:
    image: ibirasa/vowvenue-frontend:latest
    ports:
      - '3001:80'
    depends_on:
      - backend

  backend:
    image: ibirasa/vowvenue-backend:latest
    ports:
      - '8001:8000'
