global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'django_app_production'
    metrics_path: /metrics
    static_configs:
      - targets: ['knot-backend.ashysea-fcb2b410.eastus.azurecontainerapps.io']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'django_app_staging'
    metrics_path: /metrics
    static_configs:
      - targets: ['knot-backend-staging.ashysea-fcb2b410.eastus.azurecontainerapps.io']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'frontend_production'
    metrics_path: /health
    static_configs:
      - targets: ['knot-frontend.ashysea-fcb2b410.eastus.azurecontainerapps.io']
    scrape_interval: 60s
    scrape_timeout: 10s

  - job_name: 'frontend_staging'
    metrics_path: /health
    static_configs:
      - targets: ['knot-frontend-staging.ashysea-fcb2b410.eastus.azurecontainerapps.io']
    scrape_interval: 60s
    scrape_timeout: 10s

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://knot-frontend.ashysea-fcb2b410.eastus.azurecontainerapps.io
        - https://knot-backend.ashysea-fcb2b410.eastus.azurecontainerapps.io
        - https://knot-frontend-staging.ashysea-fcb2b410.eastus.azurecontainerapps.io
        - https://knot-backend-staging.ashysea-fcb2b410.eastus.azurecontainerapps.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
