name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
# ...existing code...
jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          cd vowvenue_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd vowvenue_backend
          python manage.py test

      - name: Install frontend dependencies
        run: |
          cd vow-venue-frontend
          npm ci

      - name: Run frontend tests
        run: |
          cd vow-venue-frontend
          npm test -- --watchAll=false

      - name: Dependency vulnerability scan (backend)
        run: |
          pip install safety
          safety check -r vowvenue_backend/requirements.txt

      - name: Dependency vulnerability scan (frontend)
        run: |
          cd vow-venue-frontend
          npm audit --audit-level=high

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t $DOCKER_USERNAME/knot-backend ./vowvenue_backend

      - name: Build frontend image
        run: docker build -t $DOCKER_USERNAME/knot-frontend ./vow-venue-frontend

      # ...existing code...
      - name: Container image scan (backend)
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/knot-backend

      - name: Container image scan (frontend)
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/knot-frontend
        # ...exi
        run: docker push $DOCKER_USERNAME/knot-backend

      - name: Push frontend image
        run: docker push $DOCKER_USERNAME/knot-frontend

  deploy-production:
    needs: build-test-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v2

      - name: Azure Login using Service Principal
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Backend to Azure Container App
        run: |
          az containerapp update \
            --name knot-backend \
            --resource-group knotnest-rg \
            --image $DOCKER_USERNAME/knot-backend \
            --cpu 0.5 \
            --memory 1.0Gi

      - name: Deploy Frontend to Azure Container App
        run: |
          az containerapp update \
            --name knot-frontend \
            --resource-group knotnest-rg \
            --image $DOCKER_USERNAME/knot-frontend \
            --cpu 0.5 \
            --memory 1.0Gi

  post-deployment-verification:
    needs: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: Check Backend Health
        run: curl -f https://knot-backend.ashysea-fcb2b410.eastus.azurecontainerapps.io || exit 1

      - name: Check Frontend Health
        run: curl -f https://knot-frontend.ashysea-fcb2b410.eastus.azurecontainerapps.io || exit 1
