name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - 'vow-venue-frontend/**'
      - 'vowvenue_backend/**'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [main]

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ad5c80fb-4e68-4158-90c5-60e23c034e76
  VERSION: ${{ github.sha }}
  RESOURCE_GROUP: knotnest-rg
  FRONTEND_APP: knot-frontend
  BACKEND_APP: knot-backend

permisions:
  contents: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG
        run: |
          mkdir -p ./artifacts
          echo "## $(date +'%Y-%m-%d') - Version ${VERSION:0:7}" > ./artifacts/CHANGELOG.md
          echo "### Changes" >> ./artifacts/CHANGELOG.md
          git log --pretty=format:"- %s (%h)" --reverse HEAD^..HEAD >> ./artifacts/CHANGELOG.md
          echo "" >> ./artifacts/CHANGELOG.md


      - name: Upload CHANGELOG
        uses: actions/upload-artifact@v4
        with:
          name: CHANGELOG
          path: ./artifacts/CHANGELOG.md
          retention-days: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install backend dependencies
        working-directory: ./vowvenue_backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: ./vowvenue_backend
        run: python manage.py test

      - name: Backend security scan
        working-directory: ./vowvenue_backend
        run: |
          pip install safety
          safety check -r requirements.txt --output-file safety-report.json || true
        continue-on-error: true
      - name: Upload backend security report
        uses: actions/upload-artifact@v4
        with:
          name: backend-security-report
          path: vowvenue_backend/safety-report.json
          retention-days: 1
          if-no-files-found: warn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'vow-venue-frontend/package-lock.json'

      - name: Install frontend dependencies
        working-directory: ./vow-venue-frontend
        run: |
          if [ ! -f "package-lock.json" ]; then
            npm install --package-lock-only
          fi
          npm ci

      - name: Run frontend tests
        working-directory: ./vow-venue-frontend
        run: npm test -- --watchAll=false --ci

      - name: Frontend security scan
        working-directory: ./vow-venue-frontend
        run: npm audit --audit-level=high --json > npm-audit.json || true
        continue-on-error: true

      - name: Upload frontend security report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-security-report
          path: vow-venue-frontend/npm-audit.json
          retention-days: 1
          if-no-files-found: warn

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
          install: true
          use: true

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./vowvenue_backend
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_APP }}:${{ env.VERSION }}
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_APP }}:latest
          cache-from: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_APP }}:buildcache
          cache-to: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_APP }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./vow-venue-frontend
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_APP }}:${{ env.VERSION }}
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_APP }}:latest
          cache-from: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_APP }}:buildcache
          cache-to: type=registry,ref=${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_APP }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  deploy-production:
    needs: build-test-scan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend
        run: |
          az containerapp update \
            --name ${{ env.BACKEND_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_APP }}:${{ env.VERSION }} \
            --cpu 0.5 \
            --memory 1.0Gi \
            --query "{name:name, image:properties.template.containers[0].image, state:properties.provisioningState}"

      - name: Deploy frontend
        run: |
          az containerapp update \
            --name ${{ env.FRONTEND_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_APP }}:${{ env.VERSION }} \
            --cpu 0.5 \
            --memory 1.0Gi \
            --query "{name:name, image:properties.template.containers[0].image, state:properties.provisioningState}"

      - name: Verify deployments
        run: |
          az containerapp revision list \
            --name ${{ env.FRONTEND_APP }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query "[].{revision:name, image:properties.template.containers[0].image, active:properties.active, createdTime:properties.createdTime}" \
            --output table
  create-release:
    needs: deploy-production
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: '*'
          merge-multiple: true

      - name: Prepare release assets
        run: |
          mkdir -p ./artifacts
          mkdir -p ./artifacts
          [ -f "./artifacts/CHANGELOG.md" ] || echo "No CHANGELOG available" > ./artifacts/CHANGELOG.md
          [ -f "./artifacts/safety-report.json" ] || echo "{}" > ./artifacts/safety-report.json
          [ -f "./artifacts/npm-audit.json" ] || echo "{}" > ./artifacts/npm-audit.json
          echo "Release assets prepared:"
          ls -la ./artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${VERSION:0:7}
          name: Release ${VERSION:0:7}
          bodyFile: ./artifacts/CHANGELOG.md
          artifacts: './artifacts/*.json'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: false
          prerelease: false
          commit: ${{ github.sha }}
          generateReleaseNotes: false

  