name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python and install backend dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Backend Dependencies
        working-directory: vowvenue_backend
        run: pip install -r requirements.txt

      # Wait for PostgreSQL to be ready
      - name: Wait for Database to be Ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for database to be ready..."
            sleep 2
          done

      # Run Backend Tests
      - name: Run Backend Tests
        working-directory: vowvenue_backend
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
        run: python manage.py test

      # Set up Node.js and install frontend dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Frontend Dependencies
        working-directory: vow-venue-frontend
        run: npm install

      # Run Frontend Tests
      - name: Run Frontend Tests
        working-directory: vow-venue-frontend
        run: npm test -- --watchAll=false

      # Scan Frontend for Vulnerabilities
      - name: Scan for Vulnerabilities (Frontend)
        working-directory: vow-venue-frontend
        run: npm audit --audit-level=high || true

      # Scan Backend for Vulnerabilities
      - name: Scan for Vulnerabilities (Backend)
        working-directory: vowvenue_backend
        run: |
          pip install safety
          safety check || true

      # Verify Docker Credentials
      - name: Verify Docker Credentials
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Docker credentials not set!"
            exit 1
          else
            echo "Docker credentials are set."
          fi

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker images for frontend and backend
      - name: Build Docker Images (Frontend)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vowvenue-frontend:latest ./vow-venue-frontend

      - name: Build Docker Images (Backend)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vowvenue-backend:latest ./vowvenue_backend

      # Push Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vowvenue-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vowvenue-backend:latest

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy scan
        run: trivy image --exit-code 1 --severity HIGH vowvenue-backend:latest

      # Deploy to production (SSH or other deployment method)
      - name: Deploy to Production
        run: |
          ssh user@your-production-server "docker pull ${{ secrets.DOCKER_USERNAME }}/vowvenue-frontend:latest && docker pull ${{ secrets.DOCKER_USERNAME }}/vowvenue-backend:latest && docker-compose up -d"

      # Log out from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout
